### ISSUE TITLE
skips files and directories prefixed with `_`

### ISSUE THREAD

**Issue by bcullman** [kolodny/crlf#5]
files ending in underscore are skipped.

**Comment by mhassan1** [comment]
Can you give an example of this? Also, OS, node version, etc.

**Comment by bcullman** [comment]
given a directory like this:

```
testdir/
├── _underscoredir
│   ├── _underscorefile.txt
│   └── innertestdir
│       └── _innerunderscorefile.txt
├── _underscoretestfile.txt
└── testfile.txt
```
running `crlf testdir/*` returns only

```
CRLF testdir/_underscoretestfile.txt
CRLF testdir/testfile.txt
```

OS: macOS High Sierra, 10.13.2
node: 8.6.0

**Comment by mhassan1** [comment]
If your goal is to recurse into the directory, then you need to use a globstar and quotes:

`crlf "testdir/**/*"`

The reason for the quotes is that your shell may not interpret `testdir/**/*` the way you want it to. You need to put it in quotes so that it doesn't get interpreted at all and gets passed directly to `crlf` as is.

**Comment by bcullman** [comment]
yup. this works. closing issue.
